rusda
=======
## Interface to USDA databases

## Description
An interface to the web service methods provided by the United States Department of Agriculture (USDA). The Agricultural Research Service (ARS) provides a large set of databases. The current version of the package holds interfaces to the Systematic Mycology and Microbiology Laboratory (SMML), which consists of four databases: Fungus-Host Distributions, Specimens, Literature and the Nomenclature database. It provides functions for querying these databases. The main function is \code{associations}, which allows searching for fungus-host combinations.

## Get rusda
From CRAN
```r
install.packages("rusda")
```
or from rOpenSci
```r
install.packages("devtools")
library("devtools")

install_github("ropensci/rusda")
```
And load rusda
```r
library("rusda")
```
## Example 1
In the following example, we want to search for the host of a fungus (Rosellinia ligniaria) and the fungal associations for a give host (Fagus sylvatica). From our expert knowledge, we already know that these two species are associated. Let us see, wheather the USDA Fungus-Hosts Distributions database confirms this knowledge. 
We first specify the input species vectors. In this case they they are only one element long (they are allowed to be longer, too).
```r
host <- "Fagus sylvatica"
fungus <- "Rosellinia aquila"
```
Then we search for the associations and look at the output. Since we are interested in "real" species names we choose the 'clean' output. We want the full possible list of associations so we choose 'synonyms=TRUE'. 
```r
fungi <- associations(x = host, database = "both", clean = TRUE, syn_include = TRUE, spec_type = "plant", process = TRUE)
hosts <- associations(x = fungus, database = "both", clean = TRUE, syn_include = TRUE, spec_type = "fungus", process = TRUE)

head(fungi$association$`Fagus sylvatica`)
head(hosts$association$`Rosellinia aquila`)
```

```
## > head(fungi$association$`Fagus sylvatica`)
## [1] "Polyporus squamosus"       "Absidia glauca"            "Acia stenodon"            
## [4] "Acrogenospora megalospora" "Actinocladium rhodosporum" "Actinonema fagicola"

## > head(hosts$association$`Rosellinia aquila`)
## [1] "Acer pseudoplatanus" "Acer rubrum"         "Acer sp."            "Alnus incana"       
## [5] "Alnus rubra"         "Asclepias sp." 
```

Now we want to check if our initial knowledge is correct:
```r
cat("Is R. aqulia a fungus growing on F. sylvatica? \n", is.element("Rosellinia aquila", pathogens$association[[1]]))
cat("Is F. sylvatica a host for R. aqulia?\n", is.element("Fagus sylvatica", hosts$association[[1]]))
```

```
## > cat("Is R. aqulia a fungus growing on F. sylvatica? \n", is.element("Rosellinia aquila",
## pathogens$association[[1]]))
## Is R. aqulia a fungus growing on F. sylvatica? 
##  TRUE
## > cat("Is F. sylvatica a host for R. aqulia?\n", is.element("Fagus sylvatica", hosts$association[[1]]))
## Is F. sylvatica a host for R. aqulia?
##  TRUE
```
Our expert knowledge is excellent.

## Example 2
We want to know the mean number of associations for a group, e.g. the Polyporales. Lets create a species input vector with Linnean species names derived from GenBank. In a first step we might want to check how many species are deposited in the database.
```r
polyporus <- c("Polyporus_admirabilis", "Polyporus_alveoaris", "Polyporus_americanus", "Polyporus_arcularius", "Polyporus_brumalis", "Polyporus_chozeniae", "Polyporus_ciliatus", "Polyporus_corylinus", "Polyporus_craterellus", "Polyporus_dictyopus", "Polyporus_favescens", "Polyporus_fraxineus", "Polyporus_gayanus", "Polyporus_grammocephalus", "Polyporus_guianensis", "Polyporus_lepideus", "Polyporus_leprieurii", "Polyporus_leptocephalus", "Polyporus_longiporus", "Polyporus_melanopus", "Polyporus_meridionalis", "Polyporus_pinsitus", "Polyporus_pseudobetulinus", "Polyporus_radicatus", "Polyporus_rhizophilus", "Polyporus_squamosus", "Polyporus_squamulosus", "Polyporus_submelanopus", "Polyporus_subvarius", "Polyporus_tenuiculus", "Polyporus_tessellatus", "Polyporus_tricholoma", "Polyporus_tuberaster", "Polyporus_tubiformis", "Polyporus_udus", "Polyporus_umbellatus", "Polyporus_varius", "Polyporus_virgatus")

poly_meta <- meta_smml(x = polyporus, spec_type = "fungus", process = TRUE)
head(poly_meta)
```
```
## > head(poly_meta)
##                      Nomenclature Specimens Host_Fungus Literature
## Polyporus_admirabilis            1         1           1          1
## Polyporus_alveoaris              0         0           0          0
## Polyporus_americanus             0         0           0          0
## Polyporus_arcularius             1         1           1          1
## Polyporus_brumalis               1         1           1          1
## Polyporus_chozeniae              0         0           0          0
```
If we are interested in associations for this group, do we need to query associations for all Polyporus species? We can check that by firest running meta_smml and pruning the species without host data.

```
length(polyporus)                             # 38 all species
nrow(poly_meta[rowSums(poly_meta)>0,])        # 27 with data species
```
No, 27 of 38 species are supported with data ...
```r
polyporus <- rownames(poly_meta[rowSums(poly_meta)>0,])
polyporus_ass <- associations(x = polyporus, database = "both", clean = TRUE, syn_include = TRUE,
spec_type = "fungus", process = TRUE)
cat("Mean of hosts: ", mean(unlist(lapply(polyporus_ass[[2]], length))))
```
So within the genus Polyporus the mean number of host associations is:
```
## > cat("Mean of hosts: ", mean(unlist(lapply(polyporus_ass[[2]], length))))
## Mean of hosts:  22.88889
```
